/**
 * Per-review omp models.yml synthesis tests (plan 23 Task 3, AL-23-1; plan 37
 * Task 2 — capability-host base, always synthesize).
 *
 * The omp SDK (18.0.4) has NO include semantics: the ModelRegistry reads ONE
 * models.yml — `path.join(getAgentDir(), "models.yml")` (or the
 * createAgentSession `agentDir` override) — so a provider can only reach the
 * runtime through a COMPLETE synthesized file. Plan 37 deleted the baked
 * in-image models.yml, so EVERY review synthesizes its own:
 *   - the BASE is GENERATED from the App's selected image's capability hosts
 *     (the consumer resolves them from src/contracts/sandbox-images.ts and
 *     rides them in the runner input — this module cannot import the
 *     contract: the in-image runner graph stays inside src/review). The
 *     generated bytes are pinned here to the OLD baked file's body — the
 *     equivalence lock: a defaulted (zero-custom) App receives exactly the
 *     provider declarations today's base+custom merge produced, including
 *     `ark-plan`;
 *   - custom provider blocks carry baseUrl + `apiKey: CUSTOM_<ID>_API_KEY`
 *     (env-var-name reference form) + api + auth + the declared model ids;
 *   - provider KEYS and the api value are double-quoted (yamlQuote — every
 *     user-derived scalar carries the same defensive quoting); capability
 *     hosts are source-controlled and emit bare (like the old baked file);
 *   - ZERO key literals: the fixture secret never appears in the text (the
 *     key rides ONLY the exec env, never the declaration shape);
 *   - capability/base provider ids win on collision (a custom id shadowing a
 *     capability host is skipped — the store already refuses such ids) and
 *     every skip is reported through the onCollision callback (never silent);
 *   - no declarations → the base text unchanged (byte-identical);
 *   - the write helper targets /tmp/omp-agent-<uuid>/models.yml and NEVER
 *     reads an in-image base file (plan 37: no baked models.yml exists).
 */

import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import type { CustomProviderDeclaration } from "../../src/review/runtime";
import {
  capabilityHostsYaml,
  synthesizeModelsYaml,
  writePerReviewModelsYaml,
} from "../../src/review/models-synthesis";
import { getSandboxImage } from "../../src/contracts/sandbox-images";

/**
 * The omp capability base, pinned byte-for-byte (plan 37 equivalence lock):
 * EXACTLY the body the deleted baked in-image models.yml carried from
 * `providers:` down. Generated from the REGISTRY (not a file read) — a drift
 * in either the generator or the omp entry breaks this pin loudly.
 */
const EXPECTED_OMP_BASE = `providers:
  ark-plan:
    baseUrl: https://ark.cn-beijing.volces.com/api/plan
    apiKey: ARK_API_KEY
    api: anthropic-messages
    auth: apiKey
    models:
      - id: deepseek-v4-flash
        name: Deepseek v4 flash 0731
        reasoning: true
        input: [text]
        contextWindow: 1024000
        maxTokens: 65536
`;

/** The generated base under test: the registry's omp capability hosts. */
const BASE_YAML = capabilityHostsYaml(getSandboxImage("omp")!.hosts);

/** Fixture secret that must never appear in any synthesized text. */
const FIXTURE_KEY = "sk-live-fixture-12345abcdef";

const CUSTOM: CustomProviderDeclaration = {
  provider_id: "my-provider",
  base_url: "https://my-provider.example.com/v1",
  api: "openai-completions",
  model_ids: ["my-model-1", "my-model-2"],
};

describe("capabilityHostsYaml (plan 37 Task 2 — the registry-generated base)", () => {
  test("the omp registry entry generates EXACTLY the old baked in-image base body (byte-equivalence lock)", () => {
    expect(BASE_YAML).toBe(EXPECTED_OMP_BASE);
  });

  test("zero key literals: the base carries env-var-NAME references only", () => {
    expect(BASE_YAML).toContain("apiKey: ARK_API_KEY");
    expect(BASE_YAML).not.toContain(FIXTURE_KEY);
    expect(BASE_YAML).not.toContain("sk-");
  });

  test("multiple hosts emit consecutive blocks under providers:, in host order", () => {
    const hosts = [
      ...(getSandboxImage("omp")?.hosts ?? []),
      {
        id: "future-host",
        catalogProviderId: "ark",
        apiKeyEnv: "FUTURE_API_KEY",
        baseUrl: "https://future.example.com/v1",
        api: "openai-completions",
        auth: "apiKey",
        models: [
          {
            id: "future-model",
            name: "Future model",
            reasoning: false,
            input: ["text", "image"],
            contextWindow: 128000,
            maxTokens: 8192,
          },
        ],
      },
    ];
    const yaml = capabilityHostsYaml(hosts);
    expect(yaml).toContain("  future-host:");
    expect(yaml).toContain("apiKey: FUTURE_API_KEY");
    expect(yaml).toContain("input: [text, image]");
    expect(yaml).toContain("reasoning: false");
    expect(yaml.indexOf("ark-plan:")).toBeLessThan(yaml.indexOf("future-host:"));
    expect(yaml).toStartWith("providers:\n");
  });
});

describe("synthesizeModelsYaml (plan 23 Task 3, AL-23-1 merged-complete file)", () => {
  test("preserves the capability base ark-plan declaration AND appends the custom provider block", () => {
    const yaml = synthesizeModelsYaml(BASE_YAML, [CUSTOM]);
    // Base preserved verbatim (the merge must be complete, not destructive).
    expect(yaml).toContain("ark-plan:");
    expect(yaml).toContain("baseUrl: https://ark.cn-beijing.volces.com/api/plan");
    expect(yaml).toContain("apiKey: ARK_API_KEY");
    expect(yaml).toContain("api: anthropic-messages");
    expect(yaml).toContain("auth: apiKey");
    expect(yaml).toContain("id: deepseek-v4-flash");
    // Custom provider block: quoted id key, baseUrl, env-var-name reference,
    // api, auth, declared model ids.
    expect(yaml).toContain('"my-provider":');
    expect(yaml).toContain(`baseUrl: "${CUSTOM.base_url}"`);
    expect(yaml).toContain("apiKey: CUSTOM_MY_PROVIDER_API_KEY");
    expect(yaml).toContain('api: "openai-completions"');
    expect(yaml).toContain("auth: apiKey");
    expect(yaml).toContain(`- id: "my-model-1"`);
    expect(yaml).toContain(`- id: "my-model-2"`);
  });

  test("ZERO custom declarations → the base text unchanged (byte-identical zero-custom path)", () => {
    expect(synthesizeModelsYaml(BASE_YAML, [])).toBe(BASE_YAML);
  });

  test("ZERO key literals: the fixture secret never appears in the synthesized text", () => {
    const yaml = synthesizeModelsYaml(BASE_YAML, [CUSTOM]);
    expect(yaml).not.toContain(FIXTURE_KEY);
    expect(yaml).not.toContain("sk-live");
  });

  test("multiple custom providers merge in declaration order, each with its own env reference", () => {
    const second: CustomProviderDeclaration = {
      provider_id: "second-one",
      base_url: "https://second.example.com/v1",
      api: "anthropic-messages",
      model_ids: ["b-model"],
    };
    const yaml = synthesizeModelsYaml(BASE_YAML, [CUSTOM, second]);
    expect(yaml.indexOf('"my-provider":')).toBeLessThan(yaml.indexOf('"second-one":'));
    expect(yaml).toContain("apiKey: CUSTOM_MY_PROVIDER_API_KEY");
    expect(yaml).toContain("apiKey: CUSTOM_SECOND_ONE_API_KEY");
    expect(yaml).toContain('api: "anthropic-messages"'); // the second custom block, quoted form
    expect(yaml).not.toContain(FIXTURE_KEY);
  });

  test("capability host ids win on collision — a custom id shadowing a capability host is skipped", () => {
    const clash: CustomProviderDeclaration = {
      ...CUSTOM,
      provider_id: "ark-plan",
      base_url: "https://evil.example.com/",
    };
    const yaml = synthesizeModelsYaml(BASE_YAML, [clash]);
    // Exactly ONE ark-plan block, and it is the CAPABILITY one (its baseUrl,
    // not the custom's) — the merge never shadows a capability declaration.
    expect(yaml.match(/^  ark-plan:/gm)).toHaveLength(1);
    expect(yaml).not.toContain("https://evil.example.com/");
    expect(yaml).toContain("baseUrl: https://ark.cn-beijing.volces.com/api/plan");
  });
  test("colliding custom ids are reported through onCollision (capability/base wins, never silent)", () => {
    const clash: CustomProviderDeclaration = {
      ...CUSTOM,
      provider_id: "ark-plan",
      base_url: "https://evil.example.com/",
    };
    const collisions: string[] = [];
    const yaml = synthesizeModelsYaml(BASE_YAML, [clash, CUSTOM], (id) => collisions.push(id));
    // The skip is reported (id only — zero key material) and the merge still
    // keeps the BASE ark-plan block while appending the non-colliding custom.
    expect(collisions).toEqual(["ark-plan"]);
    expect(yaml.match(/^  ark-plan:/gm)).toHaveLength(1);
    expect(yaml).not.toContain("https://evil.example.com/");
    expect(yaml).toContain('"my-provider":');
  });

  test("YAML 1.1 boolean-like provider ids are quoted — `on` parses as a string key, never a boolean", () => {
    const pin: CustomProviderDeclaration = {
      ...CUSTOM,
      provider_id: "on",
      model_ids: ["pin-model"],
    };
    const yaml = synthesizeModelsYaml(BASE_YAML, [pin]);
    // The key is double-quoted (a bare `on:` would parse as boolean true in
    // YAML 1.1 — a strict parser then rejects the providers map shape).
    expect(yaml).toContain('  "on":');
    expect(yaml).not.toMatch(/^  on:/m);
    expect(yaml).toContain("apiKey: CUSTOM_ON_API_KEY");
    expect(yaml).toContain(`- id: "pin-model"`);
  });

  test("a base without a top-level providers map fails loud (never a partial merge)", () => {
    expect(() => synthesizeModelsYaml("# no providers here\nother: 1\n", [CUSTOM])).toThrow(/providers/);
  });

  test("custom blocks insert inside providers: even when a later top-level section follows", () => {
    const baseWithTail = `${BASE_YAML}other:\n  stuff: true\n`;
    const yaml = synthesizeModelsYaml(baseWithTail, [CUSTOM]);
    expect(yaml).toContain("other:");
    expect(yaml).toContain("stuff: true");
    expect(yaml.indexOf('"my-provider":')).toBeLessThan(yaml.indexOf("other:"));
    expect(yaml.indexOf('"my-provider":')).toBeGreaterThan(yaml.indexOf("deepseek-v4-flash"));
  });

  test("the custom api value is quoted via yamlQuote — even when it equals the capability block's literal (QC wave-1 S-003 pin)", () => {
    const sameApiAsBase: CustomProviderDeclaration = {
      ...CUSTOM,
      provider_id: "ark-style-mirror",
      api: "anthropic-messages", // the SAME literal the capability ark-plan block carries bare
    };
    const yaml = synthesizeModelsYaml(BASE_YAML, [sameApiAsBase]);
    // The custom block emits the QUOTED form (yamlQuote, like baseUrl and
    // model ids) — a raw `api: ${decl.api}` splice would be the one
    // user-derived scalar escaping the file's defensive posture.
    expect(yaml).toContain('    api: "anthropic-messages"');
    // The capability ark-plan block stays BARE — the merge never rewrites the base.
    expect(yaml).toContain("    api: anthropic-messages");
    // Exactly one quoted and one bare api line: the two forms never blur.
    expect(yaml.match(/^    api: "anthropic-messages"$/gm)).toHaveLength(1);
    expect(yaml.match(/^    api: anthropic-messages$/gm)).toHaveLength(1);
  });

  test("quoted values with YAML-special characters are escaped, not emitted raw", () => {
    const weird: CustomProviderDeclaration = {
      ...CUSTOM,
      base_url: 'https://weird.example.com/v1?x="quoted"&y=z',
      model_ids: ['model "quoted"', "plain-model"],
    };
    const yaml = synthesizeModelsYaml(BASE_YAML, [weird]);
    // The double-quoted scalar escapes the inner quotes; the parsed value
    // round-trips — and the raw `"quoted"` splice can never break the block.
    expect(yaml).toContain(`baseUrl: "https://weird.example.com/v1?x=\\"quoted\\"&y=z"`);
    expect(yaml).toContain(`- id: "model \\"quoted\\""`);
    expect(yaml).toContain(`- id: "plain-model"`);
  });
});

describe("writePerReviewModelsYaml (plan 37 Task 2 — always synthesizes from capability hosts)", () => {
  test("ZERO-custom (defaulted App): the written file is byte-identical to the old baked base — ark-plan equivalence", async () => {
    const agentDir = await writePerReviewModelsYaml(getSandboxImage("omp")!.hosts);
    expect(agentDir).toMatch(/^\/tmp\/omp-agent-/);
    const written = readFileSync(join(agentDir, "models.yml"), "utf8");
    // The zero-custom path equivalence lock: today's base+custom merge for a
    // defaulted App produced EXACTLY this provider surface (ark-plan et al).
    expect(written).toBe(EXPECTED_OMP_BASE);
    expect(written).toContain("ark-plan:");
    expect(written).toContain("apiKey: ARK_API_KEY");
    expect(existsSync(join(agentDir, "models.yml"))).toBe(true);
    rmSync(agentDir, { recursive: true, force: true });
  });

  test("custom providers merge into the capability base inside the per-review /tmp dir", async () => {
    const agentDir = await writePerReviewModelsYaml(getSandboxImage("omp")!.hosts, [CUSTOM]);
    const written = readFileSync(join(agentDir, "models.yml"), "utf8");
    // Complete merged file: capability base + custom, zero key material.
    expect(written).toContain("ark-plan:");
    expect(written).toContain("apiKey: ARK_API_KEY");
    expect(written).toContain('"my-provider":');
    expect(written).toContain("apiKey: CUSTOM_MY_PROVIDER_API_KEY");
    expect(written).not.toContain(FIXTURE_KEY);
    rmSync(agentDir, { recursive: true, force: true });
  });

  test("custom ids colliding with a capability host are skipped with onCollision reported", async () => {
    const collisions: string[] = [];
    const agentDir = await writePerReviewModelsYaml(
      getSandboxImage("omp")!.hosts,
      [{ ...CUSTOM, provider_id: "ark-plan", base_url: "https://evil.example.com/" }],
      (id) => collisions.push(id),
    );
    const written = readFileSync(join(agentDir, "models.yml"), "utf8");
    expect(collisions).toEqual(["ark-plan"]);
    expect(written.match(/^  ark-plan:/gm)).toHaveLength(1);
    expect(written).not.toContain("https://evil.example.com/");
    rmSync(agentDir, { recursive: true, force: true });
  });
});
