// Generated by `release:prepare` — do not edit (plan 51; spec 016 §7 AD-1).
// Single writer: the value mirrors `package.json#version` (bare `X.Y.Z`);
// `release:validate` pins equality. Surfaces display the `v`-prefixed form
// (`v${APP_VERSION}`) so healthz/SPA match release tags by eye.
export const APP_VERSION = "0.1.0";
